name: Action CI

on: [push]

jobs:
    ci:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Run my own conatiner action
              uses: ./
              with:
                  who-to-greet: 'Mona the Octocat'